### ISSUE TITLE
GetCorrectOffset (19043)

### ISSUE THREAD

**Issue by lmzxyz** [dretax/GarHal_CSGO#102]
int GetCorrectOffset(CHAR* Name, ULONG BuildNumber) only supports 19041 and 19042. It's outdated for BuildNumber 19043.
How can I find these offsets for the new version?

**Comment by dretax** [comment]
https://www.vergiliusproject.com/kernels/x64/Windows%2010%20%7C%202016/2104%2021H1%20(May%202021%20Update)/_EPROCESS

i will update the code later

**Comment by lmzxyz** [comment]
Thanks a lot if I'm not mistaken they are still the same. So changing the if statement in memory.c on line 42 to the following should do the trick.
else if (BuildNumber == 19041 || BuildNumber == 19042 || BuildNumber == 19043)

**Comment by dretax** [comment]
Correct
