### ISSUE TITLE
blue screen please

### ISSUE THREAD

**Issue by afeer123** [dretax/GarHal_CSGO#104]
**Describe the issue**
A clear and concise description of what the bug/issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Windows 10 version:**
 - My version is.... [Example: 2004]

**Additional context**

kdmapper.exe is blue screen win10 20h1

**Comment by afeer123** [comment]
sorry win 21h2

**Comment by afeer123** [comment]
x64

**Comment by dretax** [comment]
Have you tried debugging the problem?

**Comment by freegocrazy** [comment]
You need to set a custom entry point in linker settings. It was something like FxDriverEntry, change it to the function name of driver entry.

**Comment by dretax** [comment]
Zzzzzzz...
