### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by eni9mv** [dretax/GarHal_CSGO#113]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'd3dx11tex.h': No such file or directory	GarhalController	C:\Users\Administrator\Desktop\csgo kernal\GarHal_CSGO-master\GarhalController\overlay.h	7

**Comment by dretax** [comment]
zzzzzzzzzzzzzzzzzzzzzzzzzz
