### ISSUE TITLE
i got bluescreen 

### ISSUE THREAD

**Issue by eni9mv** [dretax/GarHal_CSGO#114]
i made load driver with .bat file
cd %~dp0
Mapper.exe Garhal.sys
pause

after running Garhal.sys got blue screen 

any help !!??

**Comment by eni9mv** [comment]
i used kdmapper

**Comment by dretax** [comment]
If you can't map a driver properly based on the instructions then this project is not for you to be honest.
What windows version are you even on? Did you fully follow the readme?

**Comment by eni9mv** [comment]
> 
Yes I have read. i fixed that problem with patchguard but!!
when i try this command "sc start garhal" i got this message 

[SC] StartService FAILED 577:

Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.

**Comment by eni9mv** [comment]
i have windows 10 pro 22H2
