### ISSUE TITLE
What's happening with the ..imgui menu not showing up ?

### ISSUE THREAD

**Issue by lordkronos** [dretax/GarHal_CSGO#115]
As the title say it ...

Been manual mapping the driver .. and work perfectly.. 
Really glad you opted like me for a imgui menu and imguidraw.  
But i can't seems to make my menu appear at the lobby or ingame, not sure why,, trying to investigate the problem since a 30 minutes and 
still don't get it ahahaha..

**Comment by lordkronos** [comment]
I'm currently at void display() override function.
  
`void display() override
    {
        if (ImGui::IsCustomKeyPressed(VK_HOME, false))
        {
            csgo_settings::showMenu = !csgo_settings::showMenu;
        }

        if (!csgo_settings::showMenu)
        {
            return;
        }


       
        ImGui::SetMenuLocation(ImVec2(xScreen, yScreen));
        
        ImGui::Begin("All Settings", &csgo_settings::showMenu, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoClipping);
        {
            ImGuiWindow* window = ImGui::GetCurrentWindow();
            ImDrawList* draw = window->DrawList;
            ImGuiStyle* style = &ImGui::GetStyle();

            ImVec2 window_position = ImGui::GetWindowPos();
            ImRect window_background(window_position, window_position + window->SizeFull); //Calculate axes of main window (for getting correct pos in future)
         
            ImRect top_panel(ImFloor(ImVec2(window_position.x, window_position.y)), ImFloor(ImVec2(window_position.x + window->SizeFull.x, window_position.y + window->SizeFull.y * 1/16)));
            ImRect logo_panel(top_panel.Min, ImVec2(top_panel.Min.x + top_panel.GetHeight(), top_panel.Max.y));

            enum Tabs_
            {
                Tab_Info = 0,
                Tab_Aimbot = 1,
                Tab_Visuals = 2
            };
            static int CurrentTab = 0;
            ImGui::SetCursorPos(ImVec2(0, 0));
            ImGui::SetNextWindowBgAlpha(1);
            ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0, 0));
            ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0, 0));
            ImGui::BeginChild("TabsChild##Top", top_panel.GetSize(), true, ImGuiWindowFlags_NoClipping);            
            {
                ImGuiWindow* chwindow = ImGui::GetCurrentWindow();

                ImRect tabs_panel(ImVec2(logo_panel.Max.x, top_panel.Min.y), top_panel.Max);
                ImRect tab_one(ImFloor(tabs_panel.Min), ImFloor(ImVec2(tabs_panel.Min.x + tabs_panel.GetWidth() * 0.5f, tabs_panel.Max.y)));
                ImRect tab_two(ImFloor(ImVec2(tab_one.Max.x, tabs_panel.Min.y)), ImFloor(tabs_panel.Max));

                ImGui::SetCursorPos(ImVec2(0, 0));
                ImGui::BeginGroup();
                ImGui::PushFont(mapFont[(int)(top_panel.GetHeight() * 0.75f)]);
                if (ImGui::TabNew("##Logo", CurrentTab == Tab_Info, logo_panel.GetSize(), LogoTexture))
                    CurrentTab = Tab_Info;
                ImGui::SameLine();

                if (ImGui::TabNew("Aimbot", CurrentTab == Tab_Aimbot, tab_one.GetSize()))
                    CurrentTab = Tab_Aimbot;

                ImGui::SameLine();
                if (ImGui::TabNew("Visuals", CurrentTab == Tab_Visuals, tab_two.GetSize()))
                    CurrentTab = Tab_Visuals;
                ImGui::PopFont();
                ImGui::EndGroup();
            }
            ImGui::EndChild();
            ImGui::PopStyleVar(2);
            ImGui::Spacing();
            bool border = true;

            if (CurrentTab == Tab_Info)
            {
                ImGui::BeginChild("Info", ImVec2(0, 0), border, ImGuiWindowFlags_NoClipping | ImGuiWindowFlags_AlwaysUseWindowPadding);
                {
                    render_settings();
                }
                ImGui::EndChild();
            }
            else if (CurrentTab == Tab_Aimbot)
            {
                ImGui::BeginChild("Aimbot", ImVec2(0, 0), border, ImGuiWindowFlags_NoClipping | ImGuiWindowFlags_AlwaysUseWindowPadding);
                {
                    render_aimbot_settings();
                }
                ImGui::EndChild();
            }
            else if (CurrentTab == Tab_Visuals)
            {
                ImGui::BeginChild("Visuals", ImVec2(0, 0), border, ImGuiWindowFlags_NoClipping | ImGuiWindowFlags_AlwaysUseWindowPadding);
                {
                    render_visuals_settings();
                }
                ImGui::EndChild();
            }

        }
        ImGui::End();
        }`

Well for me i prefer VK_INSERT, so i switch that, Should i group this ..

`
        ImGui::SetMenuLocation(ImVec2(xScreen, yScreen));
        
        ImGui::Begin("All Settings", &csgo_settings::showMenu, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoClipping);
        {
            ImGuiWindow* window = ImGui::GetCurrentWindow();
            ImDrawList* draw = window->DrawList;
            ImGuiStyle* style = &ImGui::GetStyle();

            ImVec2 window_position = ImGui::GetWindowPos();
            ImRect window_background(window_position, window_position + window->SizeFull); //Calculate axes of main window (for getting correct pos in future)
         
            ImRect top_panel(ImFloor(ImVec2(window_position.x, window_position.y)), ImFloor(ImVec2(window_position.x + window->SizeFull.x, window_position.y + window->SizeFull.y * 1/16)));
            ImRect logo_panel(top_panel.Min, ImVec2(top_panel.Min.x + top_panel.GetHeight(), top_panel.Max.y));

            enum Tabs_
            {
                Tab_Info = 0,
                Tab_Aimbot = 1,
                Tab_Visuals = 2
            };
            static int CurrentTab = 0;
            ImGui::SetCursorPos(ImVec2(0, 0));
            ImGui::SetNextWindowBgAlpha(1);
            ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0, 0));
            ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0, 0));
            ImGui::BeginChild("TabsChild##Top", top_panel.GetSize(), true, ImGuiWindowFlags_NoClipping);            
            {
                ImGuiWindow* chwindow = ImGui::GetCurrentWindow();

                ImRect tabs_panel(ImVec2(logo_panel.Max.x, top_panel.Min.y), top_panel.Max);
                ImRect tab_one(ImFloor(tabs_panel.Min), ImFloor(ImVec2(tabs_panel.Min.x + tabs_panel.GetWidth() * 0.5f, tabs_panel.Max.y)));
                ImRect tab_two(ImFloor(ImVec2(tab_one.Max.x, tabs_panel.Min.y)), ImFloor(tabs_panel.Max));

                ImGui::SetCursorPos(ImVec2(0, 0));
                ImGui::BeginGroup();
                ImGui::PushFont(mapFont[(int)(top_panel.GetHeight() * 0.75f)]);
                if (ImGui::TabNew("##Logo", CurrentTab == Tab_Info, logo_panel.GetSize(), LogoTexture))
                    CurrentTab = Tab_Info;
                ImGui::SameLine();

                if (ImGui::TabNew("Aimbot", CurrentTab == Tab_Aimbot, tab_one.GetSize()))
                    CurrentTab = Tab_Aimbot;

                ImGui::SameLine();
                if (ImGui::TabNew("Visuals", CurrentTab == Tab_Visuals, tab_two.GetSize()))
                    CurrentTab = Tab_Visuals;
                ImGui::PopFont();
                ImGui::EndGroup();
            }
            ImGui::EndChild();
            ImGui::PopStyleVar(2);
            ImGui::Spacing();
            bool border = true;

            if (CurrentTab == Tab_Info)
            {
                ImGui::BeginChild("Info", ImVec2(0, 0), border, ImGuiWindowFlags_NoClipping | ImGuiWindowFlags_AlwaysUseWindowPadding);
                {
                    render_settings();
                }
                ImGui::EndChild();
            }
            else if (CurrentTab == Tab_Aimbot)
            {
                ImGui::BeginChild("Aimbot", ImVec2(0, 0), border, ImGuiWindowFlags_NoClipping | ImGuiWindowFlags_AlwaysUseWindowPadding);
                {
                    render_aimbot_settings();
                }
                ImGui::EndChild();
            }
            else if (CurrentTab == Tab_Visuals)
            {
                ImGui::BeginChild("Visuals", ImVec2(0, 0), border, ImGuiWindowFlags_NoClipping | ImGuiWindowFlags_AlwaysUseWindowPadding);
                {
                    render_visuals_settings();
                }
                ImGui::EndChild();
            }

        }
        ImGui::End();
        }`

to 

`if (csgo_settings::showMenu) {
        ImGui::SetMenuLocation(ImVec2(xScreen, yScreen));
        
        ImGui::Begin("All Settings", &csgo_settings::showMenu, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoClipping);
        {
            ImGuiWindow* window = ImGui::GetCurrentWindow();
            ImDrawList* draw = window->DrawList;
            ImGuiStyle* style = &ImGui::GetStyle();

            ImVec2 window_position = ImGui::GetWindowPos();
            ImRect window_background(window_position, window_position + window->SizeFull); //Calculate axes of main window (for getting correct pos in future)
         
            ImRect top_panel(ImFloor(ImVec2(window_position.x, window_position.y)), ImFloor(ImVec2(window_position.x + window->SizeFull.x, window_position.y + window->SizeFull.y * 1/16)));
            ImRect logo_panel(top_panel.Min, ImVec2(top_panel.Min.x + top_panel.GetHeight(), top_panel.Max.y));

            enum Tabs_
            {
                Tab_Info = 0,
                Tab_Aimbot = 1,
                Tab_Visuals = 2
            };
            static int CurrentTab = 0;
            ImGui::SetCursorPos(ImVec2(0, 0));
            ImGui::SetNextWindowBgAlpha(1);
            ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0, 0));
            ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0, 0));
            ImGui::BeginChild("TabsChild##Top", top_panel.GetSize(), true, ImGuiWindowFlags_NoClipping);            
            {
                ImGuiWindow* chwindow = ImGui::GetCurrentWindow();

                ImRect tabs_panel(ImVec2(logo_panel.Max.x, top_panel.Min.y), top_panel.Max);
                ImRect tab_one(ImFloor(tabs_panel.Min), ImFloor(ImVec2(tabs_panel.Min.x + tabs_panel.GetWidth() * 0.5f, tabs_panel.Max.y)));
                ImRect tab_two(ImFloor(ImVec2(tab_one.Max.x, tabs_panel.Min.y)), ImFloor(tabs_panel.Max));

                ImGui::SetCursorPos(ImVec2(0, 0));
                ImGui::BeginGroup();
                ImGui::PushFont(mapFont[(int)(top_panel.GetHeight() * 0.75f)]);
                if (ImGui::TabNew("##Logo", CurrentTab == Tab_Info, logo_panel.GetSize(), LogoTexture))
                    CurrentTab = Tab_Info;
                ImGui::SameLine();

                if (ImGui::TabNew("Aimbot", CurrentTab == Tab_Aimbot, tab_one.GetSize()))
                    CurrentTab = Tab_Aimbot;

                ImGui::SameLine();
                if (ImGui::TabNew("Visuals", CurrentTab == Tab_Visuals, tab_two.GetSize()))
                    CurrentTab = Tab_Visuals;
                ImGui::PopFont();
                ImGui::EndGroup();
            }
            ImGui::EndChild();
            ImGui::PopStyleVar(2);
            ImGui::Spacing();
            bool border = true;

            if (CurrentTab == Tab_Info)
            {
                ImGui::BeginChild("Info", ImVec2(0, 0), border, ImGuiWindowFlags_NoClipping | ImGuiWindowFlags_AlwaysUseWindowPadding);
                {
                    render_settings();
                }
                ImGui::EndChild();
            }
            else if (CurrentTab == Tab_Aimbot)
            {
                ImGui::BeginChild("Aimbot", ImVec2(0, 0), border, ImGuiWindowFlags_NoClipping | ImGuiWindowFlags_AlwaysUseWindowPadding);
                {
                    render_aimbot_settings();
                }
                ImGui::EndChild();
            }
            else if (CurrentTab == Tab_Visuals)
            {
                ImGui::BeginChild("Visuals", ImVec2(0, 0), border, ImGuiWindowFlags_NoClipping | ImGuiWindowFlags_AlwaysUseWindowPadding);
                {
                    render_visuals_settings();
                }
                ImGui::EndChild();
            }

        }
        ImGui::End();
        }`

Well for me i prefer VK_INSERT, so i switch that, Should i group this ..

`
        ImGui::SetMenuLocation(ImVec2(xScreen, yScreen));
        
        ImGui::Begin("All Settings", &csgo_settings::showMenu, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoClipping);
        {
            ImGuiWindow* window = ImGui::GetCurrentWindow();
            ImDrawList* draw = window->DrawList;
            ImGuiStyle* style = &ImGui::GetStyle();

            ImVec2 window_position = ImGui::GetWindowPos();
            ImRect window_background(window_position, window_position + window->SizeFull); //Calculate axes of main window (for getting correct pos in future)
         
            ImRect top_panel(ImFloor(ImVec2(window_position.x, window_position.y)), ImFloor(ImVec2(window_position.x + window->SizeFull.x, window_position.y + window->SizeFull.y * 1/16)));
            ImRect logo_panel(top_panel.Min, ImVec2(top_panel.Min.x + top_panel.GetHeight(), top_panel.Max.y));

            enum Tabs_
            {
                Tab_Info = 0,
                Tab_Aimbot = 1,
                Tab_Visuals = 2
            };
            static int CurrentTab = 0;
            ImGui::SetCursorPos(ImVec2(0, 0));
            ImGui::SetNextWindowBgAlpha(1);
            ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0, 0));
            ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0, 0));
            ImGui::BeginChild("TabsChild##Top", top_panel.GetSize(), true, ImGuiWindowFlags_NoClipping);            
            {
                ImGuiWindow* chwindow = ImGui::GetCurrentWindow();

                ImRect tabs_panel(ImVec2(logo_panel.Max.x, top_panel.Min.y), top_panel.Max);
                ImRect tab_one(ImFloor(tabs_panel.Min), ImFloor(ImVec2(tabs_panel.Min.x + tabs_panel.GetWidth() * 0.5f, tabs_panel.Max.y)));
                ImRect tab_two(ImFloor(ImVec2(tab_one.Max.x, tabs_panel.Min.y)), ImFloor(tabs_panel.Max));

                ImGui::SetCursorPos(ImVec2(0, 0));
                ImGui::BeginGroup();
                ImGui::PushFont(mapFont[(int)(top_panel.GetHeight() * 0.75f)]);
                if (ImGui::TabNew("##Logo", CurrentTab == Tab_Info, logo_panel.GetSize(), LogoTexture))
                    CurrentTab = Tab_Info;
                ImGui::SameLine();

                if (ImGui::TabNew("Aimbot", CurrentTab == Tab_Aimbot, tab_one.GetSize()))
                    CurrentTab = Tab_Aimbot;

                ImGui::SameLine();
                if (ImGui::TabNew("Visuals", CurrentTab == Tab_Visuals, tab_two.GetSize()))
                    CurrentTab = Tab_Visuals;
                ImGui::PopFont();
                ImGui::EndGroup();
            }
            ImGui::EndChild();
            ImGui::PopStyleVar(2);
            ImGui::Spacing();
            bool border = true;

            if (CurrentTab == Tab_Info)
            {
                ImGui::BeginChild("Info", ImVec2(0, 0), border, ImGuiWindowFlags_NoClipping | ImGuiWindowFlags_AlwaysUseWindowPadding);
                {
                    render_settings();
                }
                ImGui::EndChild();
            }
            else if (CurrentTab == Tab_Aimbot)
            {
                ImGui::BeginChild("Aimbot", ImVec2(0, 0), border, ImGuiWindowFlags_NoClipping | ImGuiWindowFlags_AlwaysUseWindowPadding);
                {
                    render_aimbot_settings();
                }
                ImGui::EndChild();
            }
            else if (CurrentTab == Tab_Visuals)
            {
                ImGui::BeginChild("Visuals", ImVec2(0, 0), border, ImGuiWindowFlags_NoClipping | ImGuiWindowFlags_AlwaysUseWindowPadding);
                {
                    render_visuals_settings();
                }
                ImGui::EndChild();
            }

        }
        ImGui::End();
        }
}
`

Thanks for helping me, really appreciate learning with this superb source. of you!

**Comment by lordkronos** [comment]
Ok i fixed it , wow looking so damn nice.

**Comment by dretax** [comment]
@lordkronos what was your issue?
