### ISSUE TITLE
Function detection

### ISSUE THREAD

**Issue by AlexanderQueen** [dretax/GarHal_CSGO#117]
By "flagged" you mean that these functions are detected:

No flash (Flagged)
Displays enemies on the Radar (Flagged)
Bhop (Flagged)

**Comment by lordkronos** [comment]
Correct.

**Comment by dretax** [comment]
@AlexanderQueen as @lordkronos said yes, those  value changes are flagged by VAC and will lower your trust factor or could result in a ban.
