### ISSUE TITLE
I got banned... (entire explanation and possible detection)

### ISSUE THREAD

**Issue by skhrlx** [dretax/GarHal_CSGO#118]
So, currently I'm converting the view_angles to mouse cords, and using my arduino, I never writed to meory game, and two/three month ago, I stopped to matchmaking because the game started giving me a error, "csgo settings were specified incorrectly", now i logged on my account and got a game ban, that was a untrusted ban, not overwatch, since they blocked me from matchmaking a time ago, my modified garhal don't have any function that write directly into the game, and i developed a poly engine, and i done some other ways of signature bypass (and I don't need it, since I'm on kernel and vac is as meme). So, what happened? Which detection vector they used to detect me? This don't make sense for me, and no, I never used any other cheat on that account. btw, I can bypass some league anti-cheats with an other cheat of mine, and I got game banned on VALVE, lol, that's really don't make sense for me

**Comment by dretax** [comment]
I'd not say that this is the case. If you can bypass league anti-cheats, you should know by yourself that the only actual way to find out what you got banned for is to reverse VAC and see what they added lately. There may be a possibility that they hardcoded Garhal as a flag, and search for It lately. I'd strongly say that if you definitely were only reading memory from the target process, then signature, strings, or whatever other things could have gotten you banned, but most likely overwatch.
I do not use Garhal nowadays, but I may do another long test sometime just for fun.
