### ISSUE TITLE
controller disappears, file manager gets stuck in infinite loop

### ISSUE THREAD

**Issue by abashir7866** [dretax/GarHal_CSGO#125]
**Describe the issue**
When i try to load the controller with CSGO opened nothing happens and my file manager gets stuck loading infinitely unless i force it to restart through the task manager. If i dont have CSGO opened, it asks me to open CSGO but when i do the controller disappears and my file manager gets stuck in the same infinite loop

**To Reproduce**
1. Load the driver like normal
2. Open the controller
3. Open CSGO
4. See the controller disappear

**Expected behavior**
cheat to launch like normal, i honestly dont know what that looks like as i have never got it to launch regularly

**Windows 10 version:**
 - My version is 22H2

**Comment by lordkronos** [comment]
I agree that the new version does this to me too.

**Comment by make82777** [comment]
Have you updated your windows lately? If it worked before the update, take the project files and in the version check thingy add BuildVersion == 19045 ( offsets are the same so it doesnt matter )

**Comment by dretax** [comment]
I'll initiate an update for the offsets once i have some time.
