### ISSUE TITLE
Kernel Memory Management

### ISSUE THREAD

**Issue by LoseYouNow** [dretax/GarHal_CSGO#126]
if you try to read the cs2 memory
the kernel mmcopyvirtualmemory return 0 and the status is failure

**Comment by LoseYouNow** [comment]
> this kernel is safe other game ?

i dont know

**Comment by Z-Lynx** [comment]
@LoseYouNow try rm vanguard ?

**Comment by exotikcheat** [comment]
> @LoseYouNow try rm vanguard ?

ioctl driver not work into vanguard =)

**Comment by dretax** [comment]
> if you try to read the cs2 memory the kernel mmcopyvirtualmemory return 0 and the status is failure

That's because you have probably no idea at what you are doing. Debug the code and try to make it work...
