### ISSUE TITLE
sorry ! a mistake please remove

### ISSUE THREAD

**Issue by DanielSparta** [dretax/GarHal_CSGO#127]
oops sorry mistake please remove

**Comment by WolverinDEV** [comment]
Well actually as a fun side note:  
This project initially inspired me to work on a fork for CS:GO and finally develop my own Rust based kernel driver which has been named `valthrun-driver.sys`.

In that regard a big thank you @dretax ❤️

**Comment by dretax** [comment]
@WolverinDEV I am not sure how much advantage you will gain via rust, as It is really in child shoes for kernel, even for regular production drivers.

None the less, It will be an experience.
I used TeaSpeak back in the day btw, good to see you still being active.

**Comment by WolverinDEV** [comment]
Haha the world is fucking small :D
  
Well in terms of advantage:  
It's a lot of fun and once you've your libraries (self written ofc. as you already mentioned, there is barely anything atm.) up, it's a charm to have some kind of "safety". In general it's quite similar to GarHal a fun project where I like to experiment and push the boundaries, or just to torture myself 😆.
  
If you want you can join my (Valthrun) Discord server.

**Comment by dretax** [comment]
> Haha the world is fucking small :D
>   
> Well in terms of advantage:  
> It's a lot of fun and once you've your libraries (self written ofc. as you already mentioned, there is barely anything atm.) up, it's a charm to have some kind of "safety". In general it's quite similar to GarHal a fun project where I like to experiment and push the boundaries, or just to torture myself 😆.
>   
> If you want you can join my (Valthrun) Discord server.

Yes, I have seen that the flow/structure is same as Garhal.
Eventually I will update Garhal, but I am long gone of messing with cs. 😁
