### ISSUE TITLE
Drive compile error

### ISSUE THREAD

**Issue by xuhaoa** [dretax/GarHal_CSGO#28]
Hello, sorry, I reported an error "suppose an int is returned from outside" when compiling the driver, what should I do? Wdm.h file, thank you very much.Have star

**Comment by dretax** [comment]
That doesn't seem like a valid error. Screenshot Visual Studio please.

**Comment by xuhaoa** [comment]
Spectre prompt release vulnerability library, I closed release (because it was invalid after installation), this is its error.
![error](https://user-images.githubusercontent.com/30211677/82752167-b6085c80-9dee-11ea-92a0-57d3b744eb7f.png)
![spectre](https://user-images.githubusercontent.com/30211677/82752168-b7d22000-9dee-11ea-9861-efabd2679dd7.png)

**Comment by dretax** [comment]
Spectre-mitigated libraries needs to be installed inorder to compile a driver. This must be done before installing the WDK. You can install this library from the Visual Studio installer. If you can't fix this issue, I have done a tutorial video about driver development today, and sent It to Rake, and might be out on guidedhacking.com today.

**Comment by dretax** [comment]
@xuhaoa https://guidedhacking.com/threads/windows-kernel-mode-driver-tutorial.15201/
