### ISSUE TITLE
Not Working in Windows 10 update 2004

### ISSUE THREAD

**Issue by kaushikkumarbora** [dretax/GarHal_CSGO#52]
Project Compiles without error.
Driver loads successfully.
GarhalController.exe running, but no effect on game

**Comment by Life45** [comment]
Sounds like an offset issue, i don't think it's related to windows version. Valve is updating csgo more often so i recommend checking [steamdb](https://steamdb.info/app/730/) page to see last update time and update your offsets before getting into the game.

**Comment by dretax** [comment]
+1. Please verify.

**Comment by dretax** [comment]
@kaushikkumarbora https://github.com/dretax/GarHal_CSGO/commit/01b80187e437664dd974dd5ce1dc1b33679b1391

**Comment by kaushikkumarbora** [comment]
Resolved after offset update
