### ISSUE TITLE
all_of issue

### ISSUE THREAD

**Issue by knuoe** [dretax/GarHal_CSGO#63]
Hello,

any idea why this is happening? i managed to compile it in the past, but dont know why this occures now.

![grafik](https://user-images.githubusercontent.com/70093110/90975433-714aa980-e534-11ea-8eec-ecef1894bbec.png)

Greetings

**Comment by dretax** [comment]
So you only included algorithm? I got a report from someone else aswell, similar issue.
Wonder why I am not getting It.
