### ISSUE TITLE
CRITICAL_STRUCTURE_CORRUPTION

### ISSUE THREAD

**Issue by xenu1** [dretax/GarHal_CSGO#64]
I got the cheat working with driver manual mapping and it's nice but after like 30 mins I'll get a BSOD for CRITICAL_STRUCTURE_CORRUPTION I have all the hiding and callbacks disabled. Do you know what could be happening?

**Comment by Life45** [comment]
CRITICAL_STRUCTURE_CORRUPTION bsod after some time often indicates that patchguard detected something. What do you use to manually load the driver ?

**Comment by dretax** [comment]
That might be right. Can you get me a crash dump via windbg by typing
!analyze -v
similar to here? https://github.com/dretax/GarHal_CSGO/issues/35

**Comment by xenu1** [comment]
> @xenu1
> That might be right. Can you get me a crash dump via windbg by typing
> !analyze -v
> similar to here? #35

i've now removed everything that could trigger pg so hopefully it won't happen again if it does i'll have dumps enabled this time

**Comment by dretax** [comment]
@xenu1 Let me know what you have removed, because that could give me info as well.

**Comment by xenu1** [comment]
> @xenu1 Let me know what you have removed, because that could give me info as well.

made sure to remove all the process hide and driver hide stuff and also the obregister callbacks. unsure of if it actually did anything havent tested. gonna try to add my own driver that i used for valorant.

**Comment by xenu1** [comment]
Okay so I removed all the callbacks and still received a BSOD. Only have a dump file not sure if you would want to take a look at it.

**Comment by dretax** [comment]
Ahh yea, I forgot I didn't provide alternative to PsSetLoadImageNotifyRoutine.
Patchguard checks that function.

Implementing PsGetProcessWow64Process is nothing serious, do you want me to make a good sample of It?

**Comment by xenu1** [comment]
> Ahh yea, I forgot I didn't provide alternative to PsSetLoadImageNotifyRoutine.
> Patchguard checks that function.
> 
> Implementing PsGetProcessWow64Process is nothing serious, do you want me to make a good sample of It?
 
yeah that would be awesome thanks

**Comment by dretax** [comment]
Alright.

**Comment by xenu1** [comment]
I tried using the one from this https://github.com/nbqofficial/kernel-csgo but couldn't get it working I'm a bit new to kernel D:

**Comment by dretax** [comment]
Well the easiest solution here is probably to make an IOCTL to order the Driver to find the process we are looking for.
Then use PsGetProcessWow64Process to grab the baseaddresses of the specific dlls "we need".
Once I have time I'll code It on the week.

**Comment by xenu1** [comment]
any update on this i tried a little more to add this. i got it to compile but still seems to not work. does the method to get process id also need to change?

**Comment by dretax** [comment]
Yeah sorry. I'll commit It in the morning.

**Comment by xenu1** [comment]
sounds good

**Comment by dretax** [comment]
I haven't forgotten it, I'm working on it asap, just harder on weekdays. I think i can manage to slip it in.

**Comment by xenu1** [comment]
take your time :D ill test asap when you commit

**Comment by dretax** [comment]
https://github.com/dretax/GarHal_CSGO/tree/dretax

boolean ismanualmapped probably needs an initial value. There could be mistakes. Didn't have time for the image sizes.
Try testing It see if you get a bsod at map.

**Comment by dretax** [comment]
@xenu1 fixed some other stuffs and added the size in the mean time. Let me know how it goes.

**Comment by xenu1** [comment]
Going to test right now!

**Comment by xenu1** [comment]
The driver maps fine it seems but when you run the usermode client it gives a BSOD with APC_INDEX_MISMATCH

**Comment by dretax** [comment]
Mhm. Checking right now.

**Comment by xenu1** [comment]
There was just a csgo update as well not sure if that matters

**Comment by dretax** [comment]
Alright. It's probably the MODULEENTRY GetProcessModule(PEPROCESS Process, LPCWSTR ModuleName)
function.
To verify this, can you please move the
KeStackAttachProcess(Process, &KAPC); to the beginning of the try catch, and
KeUnstackDetachProcess(&KAPC); to the end of the try catch?

If you still get a bsod the next step to do without a crashdump is to 
comment out all the code and just return an empty
MODULEENTRY ret = {0, 0};

**Comment by xenu1** [comment]
seems to already be there for me `KeStackAttachProcess(Process, &KAPC);

	__try
	{
		PPEB32 peb32 = (PPEB32)PsGetProcessWow64Process(Process);
		if (!peb32 || !peb32->Ldr)
		{
			return ret;
		}

		for (PLIST_ENTRY32 plist_entry = (PLIST_ENTRY32)((PPEB_LDR_DATA32)peb32->Ldr)->InLoadOrderModuleList.Flink;
			plist_entry != &((PPEB_LDR_DATA32)peb32->Ldr)->InLoadOrderModuleList;
			plist_entry = (PLIST_ENTRY32)plist_entry->Flink)
		{
			PLDR_DATA_TABLE_ENTRY32 pentry = CONTAINING_RECORD(plist_entry, LDR_DATA_TABLE_ENTRY32, InLoadOrderLinks);

			if (wcscmp((PWCH)pentry->BaseDllName.Buffer, ModuleName) == 0)
			{
				ret.Address = pentry->DllBase;
				ret.Size = pentry->SizeOfImage;
				return ret;
			}
		}
	}
	__except (EXCEPTION_EXECUTE_HANDLER)
	{
		DebugMessageNormal("%s: Exception, Code: 0x%X\n", __FUNCTION__, GetExceptionCode());
	}

	KeUnstackDetachProcess(&KAPC);`

**Comment by dretax** [comment]
This way:
![image](https://user-images.githubusercontent.com/1114109/92591712-b1cd5580-f29e-11ea-993c-1fc4e70f6d30.png)

**Comment by dretax** [comment]
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-kestackattachprocess

KeStackAttachProcess attaches the current thread to the address space of the process pointed to by the Process parameter. If the current thread was already attached to another process, the ApcState parameter receives the current APC state before KeStackAttachProcess attaches to the new process.

Every call to KeStackAttachProcess must be matched by a subsequent call to KeUnstackDetachProcess.

Note   Attaching a thread to a different process can prevent asynchronous I/O operations from completing and can potentially cause deadlocks. In general, the lines of code between the call to KeStackAttachProcess and the call to KeUnstackDetachProcess should be very simple and should not call complex routines or send IRPs to other drivers.

hmm....

**Comment by xenu1** [comment]
I'll give it a try

**Comment by dretax** [comment]
Wait. I'm retarded. lol. Here is the fix.

**Comment by dretax** [comment]
The first module is obviously found, but the stack is not unstacked, therefore we get an APC bsod.
![image](https://user-images.githubusercontent.com/1114109/92592405-ceb65880-f29f-11ea-9282-c6f09d15a5f4.png)

**Comment by xenu1** [comment]
That fixed that BSOD error now I am getting kmode_exception_not_handled when opening the usermode client

**Comment by dretax** [comment]
Where are you getting that?
Can you check DebugView for the error or smh?

**Comment by dretax** [comment]
So you are getting another bsod?

**Comment by xenu1** [comment]
Yeah

**Comment by xenu1** [comment]
ntoskrnl.exe+3ddf40 is where the bugcheck occurs

**Comment by xenu1** [comment]
heres a snippet of the crash dump analysis

https://pastebin.com/SqabNuPR

**Comment by dretax** [comment]
mhm. I'm thinking on where it could happen.
Also thanks for the crash dump. Can you attach the .sys file here so i can analyze it in IDA?
BUCKET_ID_FUNC_OFFSET:  ce

**Comment by xenu1** [comment]
Sure here you go [https://filebin.net/0dwfvfrqumns3zid/Garhal.sys?t=2rgw8tmy](url)

**Comment by dretax** [comment]
can i have your discord please? Seems like we are crashing further. mhm.
@xenu1

**Comment by xenu1** [comment]
playing for kda#0361

**Comment by dretax** [comment]
Fixed in https://github.com/dretax/GarHal_CSGO/pull/65.
Issue was at the changes in memory.c when I removed the reference mark.
