### ISSUE TITLE
Controller crash on launch

### ISSUE THREAD

**Issue by webinsh** [dretax/GarHal_CSGO#67]
Controller is crashing, when trying to launch it. Error - ReadRequest was corrupted
https://prnt.sc/ufd33j

**Comment by dretax** [comment]
@webinsh Thanks for the report, I haven't tested the latest commit. I'll take a look today.

**Comment by dretax** [comment]
Please apply this small change to the driver.
https://github.com/dretax/GarHal_CSGO/commit/d54a9f121458d3b6aaebf704015bea98e8157682
I wonder if the current state is causing It.

**Comment by webinsh** [comment]
Now I can't even compile a thing. It shows that function is not found(https://prnt.sc/uff6v4), but it is defined in ntos.h(https://prnt.sc/uff7q1)?

**Comment by dretax** [comment]
Thanks, I'll take a look today.

**Comment by dretax** [comment]
I can't confirm your issue. The driver compiles with either changes.
The controller works. I used kdmapper to map the driver.
I also launched the controller as admin. @webinsh

**Comment by dretax** [comment]
@webinsh I think the problem is that you are building a debug build.
Try compiling on release, furthermore always compile "ready" programs in release.
Are you on 32 or 64bit?
