### ISSUE TITLE
'all_of': identifier not found

### ISSUE THREAD

**Issue by LTSF** [dretax/GarHal_CSGO#68]
1>------ Build started: Project: GarhalController, Configuration: Release x64 ------
1>Aimbot.cpp
1>BSPFile.cpp
1>BSPParser.cpp
1>config.cpp
1>Engine.cpp
1>Entity.cpp
1>GarhalController.cpp
1>TraceRay.cpp
1>C:\Users\Administrator\Desktop\GarHal_CSGO-master\GarhalController\Matrix.hpp(80): error C3861: 'all_of': identifier not found
1>C:\Users\Administrator\Desktop\GarHal_CSGO-master\GarhalController\Matrix.hpp(80): message : 'all_of': function was not declared in the template definition context and can be found only via argument-dependent lookup in the instantiation context
1>C:\Users\Administrator\Desktop\GarHal_CSGO-master\GarhalController\Matrix.hpp(76): message : while compiling class template member function 'bool Matrix<float,3,1>::empty(void) const'
1>C:\Users\Administrator\Desktop\GarHal_CSGO-master\GarhalController\TraceRay.cpp(276): message : see reference to function template instantiation 'bool Matrix<float,3,1>::empty(void) const' being compiled
1>C:\Users\Administrator\Desktop\GarHal_CSGO-master\GarhalController\BSPStructure.hpp(91): message : see reference to class template instantiation 'Matrix<float,3,1>' being compiled
1>Done building project "GarhalController.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

If someone can help me with this i would really aprieciate it.

**Comment by dretax** [comment]
@LTSF Were you able to successfully compile?
