### ISSUE TITLE
Read Write Problem

### ISSUE THREAD

**Issue by atulkunal999** [dretax/GarHal_CSGO#70]
Your Driver in my PC is Reading correctly sometime but in not able to write any memory any solution.
i am using your driver to read and write by my own c++ program.
i had already cheeked your driver was successfully loaded and working. 
![Screenshot (80)](https://user-images.githubusercontent.com/44960066/97034404-7e126a80-1582-11eb-9e3e-4724acc6f650.png)

**Comment by dretax** [comment]
There are many flaws in here that do not make this issue feel right.
The project works perfectly for use, It's your modifications that might be the issue however.

There are many questions such as: Are you running your usermode app elevated?
What have you modified in the code?
Have you tried debuging the drivers functions using DebugView?

You have provided almost 0 amount of code. This is rarely any help.

**Comment by Life45** [comment]
Default kernel interface file that @dretax is using in this project only targets 32 bit. You are trying use this to read data from a 64 bit process so you are getting complete trash. Re-write the interface file if you intend to use it on 64 bit processes.

**Comment by dretax** [comment]
Correct.
ULONG is 4 bytes, this code doesn't work on x64 processes

**Comment by dretax** [comment]
Very authentic.
