### ISSUE TITLE
All_Of Identifier Not Found

### ISSUE THREAD

**Issue by ImJksn** [dretax/GarHal_CSGO#72]
**Describe the issue**
When attempting to compile the `GarhalController` project, `Matrix.hpp` has an alleged error on line 80. The compiler cites [C3861](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3861?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C3861)%26rd%3Dtrue&view=msvc-160) with the description that `'all_of': identifier not found`. When looking through the `Matrix.hpp` file for the declaration and definition of `m_cValues`, both are present.

**To Reproduce**
1. Clone the repo, open in VS 2019.
2. Right click the `GarhalController` project and select properties. Change to C++17 as both `Default` and C++14 both create many more errors.
3. Set project to Win32 platform and the `Release` config.
4. Attempt to build the `GarhalController` project; error will be shown.

**Expected behavior**
Expected that the project compiles without this error and produces an executable.

**Screenshots**
![image](https://user-images.githubusercontent.com/24984165/97768745-91718880-1ae2-11eb-9185-544c46821123.png)

**Windows 10 version:**
 - My version is 2004, specifically `10.0.19041 Build 19041`

**Comment by Life45** [comment]
Thanks for including all the details, it's nice to see someone still doing that. However, the same issue was reported 2 more times(as you can see [there](https://github.com/dretax/GarHal_CSGO/issues/68) and [there](https://github.com/dretax/GarHal_CSGO/issues/63)) and was fixed with a simple algorithm include. A quick check on closed issues section could have saved you from writing a whole thread :)

**Comment by ImJksn** [comment]
> Thanks for including all the details, it's nice to see someone still doing that. However, the same issue was reported 2 more times(as you can see [there](https://github.com/dretax/GarHal_CSGO/issues/68) and [there](https://github.com/dretax/GarHal_CSGO/issues/63)) and was fixed with a simple algorithm include. A quick check on closed issues section could have saved you from writing a whole thread :)

I'm super silly! I saw both the other open issues and was confused by the "include algorithm" part...but the way you phrased it of "algorithm include" made me realize it was literally `#include <algorithm>`...Just tested and compiled correctly. I'm so silly hahaha. Thank you, I'm pretty new to all this so I appreciate your help! I'll close this out. 😄

**Comment by Life45** [comment]
Haha it happens. Glad you could figure it out.

**Comment by dretax** [comment]
Thanks for taking the time to write the issue. It is still unknown to me why the project compiles at my by It self without the include. I will include It by default. Also a smaller update is coming to the repo.
