### ISSUE TITLE
Why There is no memory Allocation

### ISSUE THREAD

**Issue by atulkunal999** [dretax/GarHal_CSGO#76]
I think you can make this better by adding a simple memory allocation in your driver.
this may help in developing many more hacks.

**Comment by dretax** [comment]
@Life45 xaxaxa, first

@atulkunal999 well what would you need it for?

**Comment by dretax** [comment]
I need examples of what do you need to use it for otherwise i cant implement.

**Comment by atulkunal999** [comment]
ok you can see my Repo https://github.com/atulkunal999/pubg_mobile_memory_hacking
Where i used Your Driver To Implement a Game Hack and if i want to add magic bullet i need to allocate memory
or as another example my game process is protected and i want to inject a DLL then i want to allocate a Memory But there is a problem i can not use virtualallocEx becouse its using some type of protection.

**Comment by dretax** [comment]
I see. Its nothing hard to do honeslty. Will consider adding.

**Comment by atulkunal999** [comment]
Thank you That Would be helpful and please considering adding a simple implement.

**Comment by 2217936322** [comment]
> magic bullet

CSGO magic bullet NO!!! That’s not possible!!!The Bullet’s information is on the server!!!!!!

**Comment by dretax** [comment]
> > magic bullet
> 
> CSGO magic bullet NO!!! That’s not possible!!!The Bullet’s information is on the server!!!!!!

He is using the driver on an emulated PUBG android app.
