### ISSUE TITLE
just a better way of doing things

### ISSUE THREAD

**Issue by itsyourcracker** [dretax/GarHal_CSGO#77]
Instead of using 99999.f you could use FLT_MAX. I don't know I think it just makes it look better

**Comment by dretax** [comment]
Not sure from which part you are refering to, I am on phone but gonna check It out. Thanks.

**Comment by itsyourcracker** [comment]
https://github.com/dretax/GarHal_CSGO/blob/master/GarhalController/Aimbot.cpp

Line 119

float closest = 999999999.f;

you could change it to this 

float closest = FLT_MAX;

**Comment by dretax** [comment]
Yeah, seen in the morning, but forgot after work.
Consider it done. Thanks.
