### ISSUE TITLE
This is more of a question rather than feature request

### ISSUE THREAD

**Issue by xenu1** [dretax/GarHal_CSGO#80]
I was wondering if this aimbot would be fine on faceit serverside AC. I think for writing viewangles this requires to check the mousedx and mousedy and make sure you are sending the correct positions for these. Does the cheat already do something like this?

**Comment by Life45** [comment]
I believe Garhal doesnt currently simulate mouse movements which should be done if you are going to use in faceit. Comparing raw mouse input and viewangles should be relatively easy for faceit and could get you detected as you also said.

**Comment by dretax** [comment]
For faceit, the aimbot is not the first issue you need with. You will need a reliable, "invisible" communication first that you can use. Then start doing things step by step.

**Comment by xenu1** [comment]
> For faceit, the aimbot is not the first issue you need to deal with. You will need a reliable, "invisible" communication first that you can use. If your driver is undetected then start doing usermode things step by step.
> Be aware that faceit may pay attention to variable changes. They might check for glow struct values aswell, or different things.

was more asking if playing faceit without the client AC and just the serversided AC was safe. but thanks, I got my answers
