### ISSUE TITLE
I have mounted the driver but get this error

### ISSUE THREAD

**Issue by 1145738769** [dretax/GarHal_CSGO#82]
Addresses are 0x0. Waiting for CSGO...

**Comment by 1145738769** [comment]
I already open csgo

**Comment by dretax** [comment]
You wish to explore kernel level, but failing to use the github templates, and basic research.
If you don't take the time to write your issue down detailed why should I "waste" my time answering your question?

Usermode applications can only enstablish IOCTL connections if you are running them with administrator rights.
