### ISSUE TITLE
Driver started an error

### ISSUE THREAD

**Issue by 1145738769** [dretax/GarHal_CSGO#84]
C:\Users\Administrator>cd C:\Users\Administrator\Desktop\kdmapper-master\x64\Release

C:\Users\Administrator\Desktop\kdmapper-master\x64\Release>kdmapper.exe Garhal.sys
[<] Loading vulnerable driver
[-] Failed to get export gdi32full.NtGdiDdDDIReclaimAllocations2
[-] Failed to allocate remote image in kernel
[-] Failed to map Garhal.sys
[<] Unloading vulnerable driver

Garhal.sys is 64
kdmapper-1803-1903-master

**Windows 10 version:**
 - My version is.... [Example: 1803]

**Comment by dretax** [comment]
The kdmapper you are using is not compatible with the OS version you are using.
