### ISSUE TITLE
kdmapper bsod

### ISSUE THREAD

**Issue by Allerek** [dretax/GarHal_CSGO#90]
im using updated kdmapper https://github.com/TheCruZ/kdmapper
Driver BSODS with SECURITY_CHECK_FAILED 
Uncommented the code, renamed old function, even tried to remove the driver unload functions(as i saw on UC that its recommended) but still nothing. I guess somethings outdated?

**Comment by dretax** [comment]
"Security check failed", my best guess is the GS- parameter from my head.

**Comment by Allerek** [comment]
> "Security check failed", my best guess is the GS- parameter from my head.
Used it.
(Sorry for other language)
![image](https://user-images.githubusercontent.com/12304071/112675973-21381a80-8e68-11eb-85e2-75d4a74d3efc.png)

"My" code looks like:
![image](https://user-images.githubusercontent.com/12304071/112675999-301ecd00-8e68-11eb-8c93-b81401ac4e24.png)
![image](https://user-images.githubusercontent.com/12304071/112676015-3614ae00-8e68-11eb-962b-f21238ed0703.png)


Also, worth to tell, im using AMD processor,(R5 1600 AF), i know kdmapper uses intel driver bug, but as i was reading somewhere, it should be working with AMD too.

**Comment by dretax** [comment]
DriverUnload change doesn't really make a big difference in this case, and kinda seems a silly suggestion.

What's your windows version? To verify garhal isnt the case, please test if you can load it by test mode.

**Comment by Allerek** [comment]
20H2, in test mode everything works fine.
![image](https://user-images.githubusercontent.com/12304071/112698561-345be200-8e8a-11eb-9798-caa146320416.png)

**Comment by Allerek** [comment]
Btw, i'm an amateur, its the good way of detecting if entity is on ladder?

`bool Entity::isOnLadder()
{
	unsigned char moveType = Driver.ReadVirtualMemory<uint32_t>(ProcessId, EntityAddress + m_MoveType, sizeof(uint32_t));
	return moveType == 9;
}`

**Comment by Life45** [comment]
> Btw, i'm an amateur, its the good way of detecting if entity is on ladder?
> 
> bool Entity::isOnLadder()
> {
> unsigned char moveType = Driver.ReadVirtualMemory<uint32_t>(ProcessId, EntityAddress + m_MoveType, sizeof(uint32_t));
> return moveType == 9;
> }

Alright, that's totally irrelevant to the topic. About the crash, if you can send the crash dump maybe i can take a look and close this before dretax sees this question and gets angry lol

**Comment by dretax** [comment]
+1 about the crash dump. Also, you could take a look at the crash offset and find the crash cause using IDA.
