### ISSUE TITLE
I don't CreateFileA from User mode, when i use kdmapper TheCruZ, help me.

### ISSUE THREAD

**Issue by phucle225** [dretax/GarHal_CSGO#91]
**Describe the issue**
hDriver == INVALID_HANDLE_VALUE

**Uncomment kernel mode**
![image](https://user-images.githubusercontent.com/31835504/113268883-16670500-9302-11eb-98ce-910c9ecaf20a.png)
![image](https://user-images.githubusercontent.com/31835504/113268959-2aab0200-9302-11eb-8bfa-b5d2215be88d.png)

**UserMode**
![image](https://user-images.githubusercontent.com/31835504/113269026-3e566880-9302-11eb-9292-ec89bdd80345.png)

**Log**
![image](https://user-images.githubusercontent.com/31835504/113269152-5e862780-9302-11eb-8e20-0b9d3d681574.png)
![image](https://user-images.githubusercontent.com/31835504/113269106-54642900-9302-11eb-8823-6755cb85a051.png)
![image](https://user-images.githubusercontent.com/31835504/113269215-6cd44380-9302-11eb-9e3f-1fe3084df5b3.png)

thank you reading.

**Comment by phucle225** [comment]
oh shit, i'm sorry, i'm newbie, run administrator user mode.

**Comment by dretax** [comment]
O_o
