### ISSUE TITLE
Issue aimbot not sucess entity

### ISSUE THREAD

**Issue by phucle225** [dretax/GarHal_CSGO#92]
**Describe the issue**
I use feature aimbot smooth, but aim not success head, and when the enemy sits down.

**Screenshots**
![image](https://user-images.githubusercontent.com/31835504/114012161-2d709e80-9890-11eb-8e63-b992ff921293.png)

**Help me **
How to fix bro :(

**Comment by phucle225** [comment]
![image](https://user-images.githubusercontent.com/31835504/114012897-19796c80-9891-11eb-83bb-ec53c0ce9d39.png)

**Comment by dretax** [comment]
You cant be serious. This repo is provided as is. If you dont like something fix It yourself and do a PR. People like you who just wanna cheat and not learn anything are the most annoying ones.

**Comment by dretax** [comment]
If you tried fixing it and got stuck somewhere lemme know.

**Comment by phucle225** [comment]
Thank bro, i read deep project, and i see solution fix, i use GetBonePosition replace getHeadPosition, Thanks for your encouragement. :)))

**Comment by dretax** [comment]
See! Ezpz.
