### ISSUE TITLE
ObRegisterCallbacks error

### ISSUE THREAD

**Issue by lmzxyz** [dretax/GarHal_CSGO#93]
**Describe the issue**
ObRegisterCallbacks returns STATUS_ACCESS_DENIED

**To Reproduce**
1. Change the Entryfunction like described for manualmapping
2. Manualmap the driver with kdmapper
3. NTSTATUS reg = RegisterOBCallback(); reg == STATUS_SUCCESS is false
4. Further debugging shows reg = STATUS_ACCESS_DENIED

**Expected behavior**

STATUS_ACCESS_DENIED | The callback routines do not reside in a signed kernel binary image.

Behavior makes sense because it isn't in a signed kernel binary image, but is it supposed to fail this without creating a solution yourself or am I doing something wrong?

**Windows 10 version:**
 - My version is Windows 10 2020 October

**Comment by dretax** [comment]
Nice to see a clearly made issue.

#54 
The easiest way would be to hook a driver's OBRegisterCallback and use that for protection. I might have an idea that i can implement this week, but I am very limited on time nowadays.
