### ISSUE TITLE
Getting stuck with csgo.exe pid

### ISSUE THREAD

**Issue by ring0jke** [dretax/GarHal_CSGO#94]
Hello,

Trying to set to work your project on my pc.

Got complied everything,created service,started it. But once im trying to start controller and get pid of csgo,it fails...

Where i could look up to debug it ? 
Sounds like driver-client communition?
![driverstuck](https://user-images.githubusercontent.com/30176670/116397695-9617bf00-a82f-11eb-8358-8f8fc2700360.png)

**Comment by ring0jke** [comment]
Driver-Client communication failure?

**Comment by Life45** [comment]
In these situations i would suggest to go from basic to complicated. For example, first of all verify that you are running the controller with admin rights so it can communicate using IOCTL.

**Comment by ring0jke** [comment]
Ye,it defiently has admin rights.
and it has handle to driver 
![image](https://user-images.githubusercontent.com/30176670/116399561-bc3e5e80-a831-11eb-9582-3c6a705e067d.png)

How do i can test communication with driver?

**Comment by Life45** [comment]
As far as i know garhal already leaves debug messages when it receives a valid IOCTL request. To see them, you can use debug view from sysinternals. Be sure to check capture kernel option

**Comment by ring0jke** [comment]
So ya, thanks for idea! 

Now i can defiently see that communication is working. 
But for some reason driver cannot get the pid :( 

![image](https://user-images.githubusercontent.com/30176670/116402582-44723300-a835-11eb-8f31-a2a3dd00c7dd.png)

**Comment by Life45** [comment]
@dretax made a lot of updates since the start including manual map and im not quite familiar with them, but if you are not using manual map i would suggest to first start the driver, then start csgo because it might use PsLoadImageNotifyRoutine which gets the PID and such when they get loaded the first time.

**Comment by ring0jke** [comment]
@Life45  that was a core of the problem 👍 
So i just restarted csgo and it perfectly works :) 🥇 
Issue solved

**Comment by NotJareks** [comment]
hey I got this same isseu but restarting csgo doesnt do the trick for me anyone who can help me out?
