### ISSUE TITLE
Kernel_security_check_failure bsod

### ISSUE THREAD

**Issue by trolloos** [dretax/GarHal_CSGO#96]
Hello I have OS build 19041.928 and I can't manual map the driver using KDmapper or UMAP, for some reason it instantly blue screens. The cheat works fine otherwise with testmode. All my build options are exactly the same as well with GS- security check disabled.
 
 
 EDIT:  I changed the DriverEntry point in the project linker settings to fix this

**Comment by zhivko-zh** [comment]
Hello, I had the same issue and apply the same fix, but now it can't be handled by the GarhalController. Can you help me please?
Thank you in advance!

**Comment by dretax** [comment]
Have you come to a solution to your issue?

**Comment by zhivko-zh** [comment]
Hello, I have the same problem, I tried to set an entry point and some other things, but without success. I apologize for the stupid question, but is there a way to start the service before any of the anti-cheat services and possibly be deceived. I am a Devops engineer, so for now I do not have the necessary knowledge in the development of kernel services, I will be grateful if you can help me.
Thank you in advance!

**Comment by dretax** [comment]
Hello,

Judging by your question you wish to bypass Valorant's AC which acts as a rootkit, and launches on your PC at boot.
I'd suggest you reading up on articles, and forums on what people have already posted as information, or you could just actually reverse their driver by yourself, and see what they are doing....................... You would need an EFI driver as a start.

As for your issue WinDbg/Crashdumps is always the answer with that little amount of information you guys are posting.

My tingling senses from @guidedhacking should tell you how much we hate this sort of "wanna bypass this in a day" attitude.
With this reverse engineering experience I'd highly do not suggest you to mess around in kernel, there is no actual point.
**This is a startup project that was my first public kernel project to help people start somewhere who are already having some sort of experience. This just won't be enough.**

Go from little to big. Cheat on games without AC, then go to VAC, BE, EAC, FaceIt, Vanguard. We have many useful posts on guidedhacking.com .

**Comment by zhivko-zh** [comment]
Thanks a lot for the answer, I will look at the articles in the forum.
