### ISSUE TITLE
Has anyone ever got this working with kdmapper on 20H2?

### ISSUE THREAD

**Issue by 18601673727** [dretax/GarHal_CSGO#99]
My setup checklist:
- Rename the function inside `garhal.c` from `DriverEntry` to `DriverInitialize`
- Comment line `pDriverObject->DriverUnload = UnloadDriver;`
- Comment block `NTSTATUS UnloadDriver(PDRIVER_OBJECT pDriverObject) {...}`
- Add line `#define _NO_CRT_STDIO_INLINE` inside `hide.h`
- C++ -> Code Generation -> Security Check -> set to `/GS-`
- Linker -> Command Line -> add `/INTEGRITYCHECK`
- Inf2Cat -> Use Local Time -> set `/uselocaltime`
- Successfully compiled the driver & copy the outputs to vmware

Finally, in admin mode powershell, type `.\kdmapper.exe .\Garhal.sys`, BSOD immediately due to `KERNEL_SECURITY_CHECK_FAILURE`.

Minidump file: [062721-6078-01.zip](https://github.com/dretax/GarHal_CSGO/files/6720531/062721-6078-01.zip)

**Comment by dretax** [comment]
Thanks for the minidump. Will take a look soon. I assume you are using an updated kdmapper?

**Comment by Life45** [comment]
You need to set a custom entry point in linker settings. It was something like FxDriverEntry, change it to the function name of driver entry.

**Comment by 18601673727** [comment]
> Thanks for the minidump. Will take a look soon. I assume you are using an updated kdmapper?

For sure mr, this's what i'm using https://github.com/TheCruZ/kdmapper

**Comment by Life45** [comment]
@18601673727 Did you try what i said ?

**Comment by 18601673727** [comment]
> @18601673727 Did you try what i said ?

Yes, and it perfectly solved this issue, now I'm struggling with the config part, closing anyway thanks for the kind helps!

**Comment by leidadpig** [comment]
May I ask what "Add line #define _NO_CRT_STDIO_INLINE inside hide.h" for? I don't understand what is the purpose doing this for.
Thanks

**Comment by dretax** [comment]
@leidadpig I'm not sure what was the case in his scenario, but I can lead you to some articles to get a better understanding. Read them in order.

https://www.codeproject.com/Articles/22642/What-Every-Computer-Programmer-Should-Know-About-W
https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-change-history-2003-2015?redirectedfrom=MSDN&view=msvc-170
https://www.solomonsklash.io/smaller-c-payloads-on-windows.html?fbclid=IwAR2cbOGJT68JAO1coT2SsUChDD1-JNhx6XbCs33zUC3tY8VYgVcaWUvt5g8
